# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/main_bd/main_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd || ORIG_REF_NAME==main_bd} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_adaptiveFilter_0_0/main_bd_adaptiveFilter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_adaptiveFilter_0_0 || ORIG_REF_NAME==main_bd_adaptiveFilter_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_processing_system7_0_0/main_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_processing_system7_0_0 || ORIG_REF_NAME==main_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_bram_ctrl_0_0/main_bd_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==main_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_blk_mem_gen_0_0/main_bd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==main_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_xbar_0/main_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_xbar_0 || ORIG_REF_NAME==main_bd_xbar_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_ps7_0_axi_periph_0/main_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_rst_ps7_0_50M_0/main_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==main_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_1/main_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_1 || ORIG_REF_NAME==main_bd_auto_pc_1} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_0/main_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_0 || ORIG_REF_NAME==main_bd_auto_pc_0} -quiet] -quiet

# XDC: d:/Sundries/GithubProject/POD-DANC/vivado/test_bram/test_bram.gen/sources_1/bd/main_bd/main_bd_ooc.xdc
