# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_processing_system7_0_0 || ORIG_REF_NAME==main_processing_system7_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_gpio_0_0/main_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_gpio_0_0 || ORIG_REF_NAME==main_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main/ip/main_xlconcat_0_0/main_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlconcat_0_0 || ORIG_REF_NAME==main_xlconcat_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_iic_0_0/main_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_iic_0_0 || ORIG_REF_NAME==main_axi_iic_0_0} -quiet] -quiet

# IP: bd/main/ip/main_d_axi_i2s_audio_0_0/main_d_axi_i2s_audio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_d_axi_i2s_audio_0_0 || ORIG_REF_NAME==main_d_axi_i2s_audio_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_dma_0_0/main_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_dma_0_0 || ORIG_REF_NAME==main_axi_dma_0_0} -quiet] -quiet

# IP: bd/main/ip/main_xbar_0/main_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xbar_0 || ORIG_REF_NAME==main_xbar_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_interconnect_0_0/main_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_interconnect_0_0 || ORIG_REF_NAME==main_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/main/ip/main_xlconstant_0_0/main_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlconstant_0_0 || ORIG_REF_NAME==main_xlconstant_0_0} -quiet] -quiet

# IP: bd/main/ip/main_rst_ps7_0_100M_0/main_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_rst_ps7_0_100M_0 || ORIG_REF_NAME==main_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/main/ip/main_xbar_1/main_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xbar_1 || ORIG_REF_NAME==main_xbar_1} -quiet] -quiet

# IP: bd/main/ip/main_ps7_0_axi_periph_0/main_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main/ip/main_blk_mem_gen_0_0/main_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_blk_mem_gen_0_0 || ORIG_REF_NAME==main_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_bram_ctrl_0_0/main_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_bram_ctrl_0_0 || ORIG_REF_NAME==main_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/main/ip/main_adaptiveFilter_0_2/main_adaptiveFilter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_adaptiveFilter_0_2 || ORIG_REF_NAME==main_adaptiveFilter_0_2} -quiet] -quiet

# IP: bd/main/ip/main_auto_us_0/main_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_us_0 || ORIG_REF_NAME==main_auto_us_0} -quiet] -quiet

# IP: bd/main/ip/main_auto_us_1/main_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_us_1 || ORIG_REF_NAME==main_auto_us_1} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_0/main_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_pc_0 || ORIG_REF_NAME==main_auto_pc_0} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_6/main_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_pc_6 || ORIG_REF_NAME==main_auto_pc_6} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_1/main_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_pc_1 || ORIG_REF_NAME==main_auto_pc_1} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_2/main_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_pc_2 || ORIG_REF_NAME==main_auto_pc_2} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_3/main_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_pc_3 || ORIG_REF_NAME==main_auto_pc_3} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_4/main_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_pc_4 || ORIG_REF_NAME==main_auto_pc_4} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_5/main_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_auto_pc_5 || ORIG_REF_NAME==main_auto_pc_5} -quiet] -quiet

# IP: bd/main/ip/main_s00_mmu_0/main_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_s00_mmu_0 || ORIG_REF_NAME==main_s00_mmu_0} -quiet] -quiet

# XDC: /home/gc635/Documents/POD-DANC/vivado/audio_dma/audio_dma.gen/sources_1/bd/main/main_ooc.xdc
