# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/main_bd/main_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd || ORIG_REF_NAME==main_bd} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_processing_system7_0_0/main_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_processing_system7_0_0 || ORIG_REF_NAME==main_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_gpio_0_0/main_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_gpio_0_0 || ORIG_REF_NAME==main_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_xbar_1/main_bd_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_xbar_1 || ORIG_REF_NAME==main_bd_xbar_1} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_5/main_bd_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_5 || ORIG_REF_NAME==main_bd_auto_pc_5} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_0/main_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_0 || ORIG_REF_NAME==main_bd_auto_pc_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_1/main_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_1 || ORIG_REF_NAME==main_bd_auto_pc_1} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_2/main_bd_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_2 || ORIG_REF_NAME==main_bd_auto_pc_2} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_3/main_bd_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_3 || ORIG_REF_NAME==main_bd_auto_pc_3} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_4/main_bd_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_4 || ORIG_REF_NAME==main_bd_auto_pc_4} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_ps7_0_axi_periph_0/main_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_rst_ps7_0_50M_0/main_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==main_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_d_axi_i2s_audio_0_0/main_bd_d_axi_i2s_audio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_d_axi_i2s_audio_0_0 || ORIG_REF_NAME==main_bd_d_axi_i2s_audio_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_dma_0_0/main_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_dma_0_0 || ORIG_REF_NAME==main_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_xbar_0/main_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_xbar_0 || ORIG_REF_NAME==main_bd_xbar_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_us_0/main_bd_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_us_0 || ORIG_REF_NAME==main_bd_auto_us_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_us_1/main_bd_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_us_1 || ORIG_REF_NAME==main_bd_auto_us_1} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_auto_pc_6/main_bd_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_auto_pc_6 || ORIG_REF_NAME==main_bd_auto_pc_6} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_interconnect_0_0/main_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_interconnect_0_0 || ORIG_REF_NAME==main_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_xlconcat_0_0/main_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_xlconcat_0_0 || ORIG_REF_NAME==main_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_iic_0_0/main_bd_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_iic_0_0 || ORIG_REF_NAME==main_bd_axi_iic_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_xlconstant_0_0/main_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_xlconstant_0_0 || ORIG_REF_NAME==main_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_bram_ctrl_0_0/main_bd_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==main_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_blk_mem_gen_0_0/main_bd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==main_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_adaptiveFilter_0_0/main_bd_adaptiveFilter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_adaptiveFilter_0_0 || ORIG_REF_NAME==main_bd_adaptiveFilter_0_0} -quiet] -quiet

# XDC: /home/gc635/Documents/POD-DANC/vivado/audio_dma_7020/audio_dma_7020.gen/sources_1/bd/main_bd/main_bd_ooc.xdc
