# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Sundries/GithubProject/POD-DANC/vivado/audio_dma/audio_dma.srcs/sources_1/bd/main/ip/main_xbar_0/main_xbar_0.xci
# IP: The module: 'main_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Sundries/GithubProject/POD-DANC/vivado/audio_dma/audio_dma.gen/sources_1/bd/main/ip/main_xbar_0/main_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Sundries/GithubProject/POD-DANC/vivado/audio_dma/audio_dma.srcs/sources_1/bd/main/ip/main_xbar_0/main_xbar_0.xci
# IP: The module: 'main_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Sundries/GithubProject/POD-DANC/vivado/audio_dma/audio_dma.gen/sources_1/bd/main/ip/main_xbar_0/main_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
