# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gc635/Documents/POD-DANC/vivado/audio_dma/audio_dma.srcs/sources_1/bd/main/ip/main_auto_pc_2/main_auto_pc_2.xci
# IP: The module: 'main_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gc635/Documents/POD-DANC/vivado/audio_dma/audio_dma.gen/sources_1/bd/main/ip/main_auto_pc_2/main_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gc635/Documents/POD-DANC/vivado/audio_dma/audio_dma.srcs/sources_1/bd/main/ip/main_auto_pc_2/main_auto_pc_2.xci
# IP: The module: 'main_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gc635/Documents/POD-DANC/vivado/audio_dma/audio_dma.gen/sources_1/bd/main/ip/main_auto_pc_2/main_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
